spring:
  application:
    name: spring-boot-actuator

  jpa:
    show-sql: true
    hibernate.ddl-auto: create
    database-platform: org.hibernate.dialect.MySQLDialect

  datasource:
    url: ${project.db.url}
    username: ${project.db.user}
    password: ${project.db.password}
    driver-class-name: com.mysql.cj.jdbc.Driver

  security:
    user:
      name: ${project.admin.username}
      password: ${project.admin.password}

project:
  db:
    user: root
    password: 12345678
    url: jdbc:mysql://localhost:3306/spring_boot_extra_demo?useSSL=false
  admin:
    username: admin
    password: 123456
  app:
    jwtSecret: VeRy_secret
    jwtExpirationMs: 86400000


server:
  port: 8080

springdoc:
  packagesToScan: com.example.demo.controller
  pathsToMatch: /api/**